### PR TITLE
Upgrade to Rocket 0.2.6

### PR DESCRIPTION
**Pull request by blackghost1987**

### CODE REVIEW

**Comment by bramvdbogaerde** [comment]
Thanks for contributing, I will test your changes and merge them back in.

**Comment by bramvdbogaerde** [comment]
I'm sorry, I didn't have much time to look at this yet. I will try to take a look at it next week

**Comment by bramvdbogaerde** [comment]
Merged! I'm sorry for the delay.

**Comment by blackghost1987** [comment]
Thanks, no problem. Also works with latest Rocket 0.2.8 FYI. Can't wait for the Rocket 0.3 release, but that will require a lot more changes though :)

**Pull request merged**
